// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xyltmkattzzgcsqcklps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5bHRta2F0dHp6Z2NzcWNrbHBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzNDk5NzEsImV4cCI6MjA0OTkyNTk3MX0.tF-P93fcO76i1wCAzINgiQFpKpuu0eYmSrZxFXUe0jE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);